---
blank_issues_enabled: false
contact_links:
  -
    about: "Please ask and answer usage questions on Stack Overflow."
    name: Question
    url: "https://stackoverflow.com/questions/tagged/lightweight-charts"
  -
    about: "Alternatively, you can use the TradingView Community Discord."
    name: Chat
    url: "https://discord.gg/UC7cGkvn4U"
